### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by TheDogg** [fru1tstand/qbittorrent-exporter#11]
Hi, how can I install this exporter? I'm looking to have qbittorrent stats in grafana as the end goal, I can't figure out how to run this exporter, are there any instructions ?

thanks

**Comment by fru1tstand** [comment]
Hi, the exporter is still under construction but if you're interested in running the current developer snapshot, do the following:

1. Download the project
2. In the root folder run `./gradlew fatJar`
3. Find the output in `build/libs` (should be named something like `qbt-exporter-fat...jar`
4. Run it using `java -jar <path to jar>`

The exporter listens on port 9561 (`localhost:9561`). You will need to change the settings (created in the same directory that you ran the `java -jar` command) in order to point to the qBittorrent web ui. The settings file doesn't explain much about the collectors (for now), but if you're wondering what specific collectors do, just enable it and refresh the exporter web page to read the HELP text.

I'll leave this issue open to create install instructions for 1.0 release.
